azure-javaee/azure-dev

- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/scaffold/spec.go
Follow-up of this comment: https://github.com/azure-javaee/azure-dev/pull/15#discussion_r1835858659
> Delete service names because they are not used

- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/java.go
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/resources/scaffold/templates/resources.bicept
This PR adds support for Azure Service Bus JMS.
> Add support for Service Bus JMS

- cli/azd/resources/scaffold/templates/resources.bicept
Change all spring related environment variable to lower-case-with-dash to avoid problems caused by UPPER_CASE_WITH_UNDERSCORE. There are 2 potential problems caused by UPPER_CASE_WITH_UNDERSCORE:
1. https://github.com/azure-javaee/azure-dev/wiki/Knowledge-Sharing#2-sometimes-the-environment-variable-not-take-effect-in-spring-boot-application
> ![image](https://github.com/user-attachments/assets/0b035585-d791-4a08-a1ff-e4e820801b3b)
2. https://github.com/Azure/azure-sdk-for-java/issues/42880#issuecomment-2469379371
> ![image](https://github.com/user-attachments/assets/a2130476-3afc-48fd-8d03-dc1a27ca8671)
> Change all spring related environment variable to lower-case-with-dash

- cli/azd/internal/auth_type.go
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/app_init_test.go
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/project/resources.go
- cli/azd/resources/scaffold/templates/resources.bicept
This PR implements the basic structure of output of resources to `azure.yaml` when enable compose mode:
- How to enable compose mode? 
* Add environment variable `AZD_ALPHA_ENABLE_COMPOSE=true` to run or debug
- How to debug `azd init`
* <img width="843" alt="image" src="https://github.com/user-attachments/assets/5c5d6704-085d-4804-94a7-47f3f6b41cf8">
- How to debug `azd up`
* Change `init` to `up` in the previous screenshot
> Output the resources to azure.yaml when enable compose mode

- cli/azd/internal/auth_type.go
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/pkg/project/resources.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/templates/resources.bicept
Follow-up of #22 . Fix error when run `azd init`.
> ![image](https://github.com/user-attachments/assets/55111239-d664-4870-8150-8bbfe89b814e)
> Fix error when run azd init

- cli/azd/pkg/project/scaffold_gen.go
Follow-up of #24.
Fix error this error: When generate  `resources.bicep` from `resources.bicep`. The '.DbMySql' is always nil.
> Fix error that ".DbMySql" not take effect in resources.bicept

- cli/azd/internal/appdetect/java.go
- cli/azd/internal/appdetect/java_test.go
Handle environment variable placeholder in property file.
> Handle environment variable placeholder in property file

- cli/azd/internal/repository/app_init.go
- cli/azd/pkg/project/resources.go
- cli/azd/pkg/project/scaffold_gen.go
This PR will fix the code to make eventhubs when in azd composability mode. Sample code see https://github.com/rujche/samples/tree/azd-enhancement-for-eventhubs.
> Fix code to support eventhubs in azd composability

- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/infra_confirm.go
Improve the prompt message for database.
Here is the screenshot of result:
> ![image](https://github.com/user-attachments/assets/282a4a7c-6944-406d-a103-59ed358961b8)
> Improve the prompt message for database

- cli/azd/internal/appdetect/java.go
1. Add log about detecting rule.
2. Avoid duplicated queue name for service bus.
Here is the screenshot of result:
> ![image](https://github.com/user-attachments/assets/85d592e3-161e-4d52-85a2-14c9c203b20c)
> Add log about detecting rule

- cli/azd/resources/scaffold/templates/resources.bicept
This PR will fix Service Bus JMS with managed identity when used in azd composability mode.
> Fix service bus jms with managed identity

- cli/azd/internal/repository/app_init.go
- cli/azd/pkg/project/resources.go
- schemas/alpha/azure.yaml.json
Update azure yaml schema to include more resource types and definitions.
> Update azure yaml schema

- cli/azd/internal/appdetect/java.go
- cli/azd/pkg/project/project.go
> Update yaml language server

- ext/vscode/package.nls.json
Update the wording of azd init in VS Code extension.
> Update the wording or azd init in VS Code extension

- cli/azd/cmd/middleware/hooks_test.go
- cli/azd/internal/appdetect/spring_boot_test.go
- cli/azd/pkg/pipeline/pipeline_manager_test.go
- cli/azd/pkg/project/importer_test.go
> Fix pipeline failures

- cli/azd/pkg/project/importer_test.go
> Fix pipeline failure

- .github/workflows/cli-ci.yml
- .github/workflows/cspell-misc.yml
- .github/workflows/go-test-for-sjad-branch.yml
- .vscode/cspell.misc.yaml
- cli/azd/.vscode/cspell.yaml
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/scaffold/bicep_env.go
- cli/azd/internal/useragent_test.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/pkg/project/scaffold_gen_environment_variables.go
1. Fix lint realted problems.
2. Enable cli-ci both main and feature/sjad branches.
> Fix lint realted problems and enable related GitHub actions

- cli/azd/internal/appdetect/spring_boot.go
- cli/azd/internal/appdetect/spring_boot_test.go
- cli/azd/pkg/project/framework_service_docker.go
1. When pack build multi-module java project, specify parent directory and sub module.
2. Fix test.
> pack build multi-module and fix test

- cli/azd/internal/auth_type.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/pkg/project/importer_test.go
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
Change auth type string to camel case.
> Change auth type string to camel case

- cli/azd/internal/auth_type.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/pkg/project/importer_test.go
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
Change auth type string from Pascal to camel case.
Related PR: https://github.com/azure-javaee/azure-dev/pull/59
> Change auth type string from Pascal to camel case

- cli/azd/internal/repository/app_init.go
When checking passwordless config for MySQL or PostgreSQL, not all service use DB, so only prompt those services used.
> Fix: not all service use DB, so only prompt those services used.

- cli/azd/resources/scaffold/templates/resources.bicept
When creating service connector, the connection name should be unique, instead of fixed.
> Fix service connector name conflict

- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/spring_boot.go
- cli/azd/internal/appdetect/spring_boot_property.go
- cli/azd/internal/appdetect/spring_boot_property_test.go
- cli/azd/internal/appdetect/spring_boot_test.go
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/infra_confirm.go
Detect database name from property file.
> Detect database name from property file

- cli/azd/test/functional/restore_test.go
- cli/azd/test/functional/telemetry_test.go
See a failed build https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4398176&view=ms.vss-test-web.build-test-results-tab&runId=51644652&resultId=100004&paneView=debug
> Fix the failed build 

- cli/azd/internal/appdetect/spring_boot.go
Enrich the rule of detecting mysql.
Tested in this sample: https://github.com/azure-javaee/azure-spring-boot-samples/pull/1
> Update todo description.

- cli/azd/internal/appdetect/spring_boot.go
Enrich rules of detecting PostgreSQL.
> Enrich rules of detecting PostgreSQL

- cli/azd/internal/appdetect/spring_boot.go
Detect spring boot app by "spring-boot-maven-plugin".
> Detect spring boot app by "spring-boot-maven-plugin"

- .github/workflows/go-test-for-sjad-branch.yml
- cli/azd/internal/appdetect/download_util.go
- cli/azd/internal/appdetect/pom.go
- cli/azd/internal/appdetect/pom_test.go
Support maven profile in simulated effective pom
> Support maven profile in simulated effective pom

- cli/azd/pkg/project/framework_service_docker.go
Resolve https://github.com/Azure/azure-dev/pull/4473#issuecomment-2587973488 by deleting SJAD created Dockerfile.
@haoozhang Could you please investigate why SJAD created Dockerfile can't be used?
> Delete SJAD created Dockerfile
