cli/azd/internal/appdetect/appdetect.go
cli/azd/internal/appdetect/java.go
cli/azd/internal/repository/app_init.go
cli/azd/internal/repository/infra_confirm.go
cli/azd/internal/scaffold/spec.go
cli/azd/resources/scaffold/base/modules/set-event-hubs-namespace-connection-string.bicep
cli/azd/resources/scaffold/templates/main.bicept
cli/azd/resources/scaffold/templates/resources.bicept

Support detect Azure Event Hubs

Support detecting event hubs by analyzing pom.xml and application.yml

---

cli/azd/internal/repository/infra_confirm.go
cli/azd/resources/scaffold/base/modules/set-event-hubs-namespace-connection-string.bicep
cli/azd/resources/scaffold/base/modules/set-servicebus-namespace-connection-string.bicep
cli/azd/resources/scaffold/base/modules/set-storage-account-connection-string.bicep
cli/azd/resources/scaffold/templates/resources.bicept

Follow up of https://github.com/azure-javaee/azure-dev/pull/6
Support detect Azure Event Hubs

Support detect Azure Event Hubs, connect by connection string.

---

cli/azd/internal/scaffold/scaffold.go
cli/azd/resources/scaffold/base/abbreviations.json
cli/azd/resources/scaffold/templates/resources.bicept

Switch to AVM for PostgreSql.
Link to sample project: https://github.com/rujche/spring-petclinic/tree/rujche/use-postgresql-support-both-password-and-passwordless

Use to AVM to support PostgreSql

---

cli/azd/internal/appdetect/java.go
cli/azd/internal/tracing/fields/fields.go

Add a span to indicate if java detector has started or finished, so that we can measure the feature usage later.

Add a span to indicate if java detector has started or finished

---

cli/azd/internal/repository/app_init.go
cli/azd/pkg/project/project.go
cli/azd/pkg/project/resources.go

This PR will output the resources detected from app init to `azure.yaml`.

Output resources in azure.yaml after app init

---

schemas/alpha/azure.yaml.json

Update `azure.yaml` schema to support `resources` section.
Currently, the AZD team adds the `resources` support in `azure.yaml` generation during azd-init phrase, but does NOT update the `azure.yaml` schema. This causes the warning when editing `azure.yaml`, just like this.
We adds this change to unblock our DB dependency scenario.
TODO: only support MySQL for now, need expand it later.

Update `azure.yaml` schema to support `resources` section

---

cli/azd/pkg/project/project.go
schemas/alpha/azure.yaml.json

+ When azd init, the generated `azure.yaml` file refers to the latest schema in the `feature/sjad` branch.
+ Just for private preview, need to revert it when merge into `azd-dev/main` branch.

Update azure.yaml schema reference for private preview

---

cli/azd/resources/scaffold/templates/resources.bicept

Only provide "SPRING_DATASOURCE_URL" environment variable when using username & password as auth type.
Here is the screenshot when using service connector:
> ![image](https://github.com/user-attachments/assets/558c6a9b-7fe5-4c05-b9c5-3d9fbe270f8e)
The  "SPRING_DATASOURCE_URL" environment variable is duplicated.

Only provide "SPRING_DATASOURCE_URL" environment variable when using username & password as auth type

---

cli/azd/pkg/project/scaffold_gen.go

This PR completes https://github.com/azure-javaee/azure-dev/pull/22. It will convert resources defined in `azure.yaml` to infraSpec for bicep infra generation.

Convert resources to infraspec

---

cli/azd/internal/repository/app_init.go
cli/azd/internal/scaffold/scaffold.go
cli/azd/pkg/project/scaffold_gen.go

This PR will fix the servicebus jms support when `azd composability` is enabled. To enable `azd composability`, run `azd config set alpha.compose on`

Fix code to support service bus jms in azd composability

---

cli/azd/internal/appdetect/java.go
cli/azd/internal/auth_type.go
cli/azd/internal/repository/app_init.go

1. Delete all "panic" introduced in this PR: https://github.com/Azure/azure-dev/pull/4473/files
2. Not return error in `(jd *javaDetector) DetectProject`, and guide users to edit azure.yaml manually.

Users can continue to use azd when java analyzer fails

---

cli/azd/internal/appdetect/java.go
cli/azd/internal/appdetect/spring_boot.go

Replace placeholders during parsing pom.xml, to make it easy to analyze pom file later.

Replace placeholders during parsing pom.xml

---

cli/azd/pkg/project/scaffold_gen_environment_variables.go
cli/azd/resources/scaffold/templates/resources.bicept

1. Set config client as `fail-fast=true`, to make it restart to reconcile if config server unavailable, until fetch from config server. This can avoid the application starts up without remote config server.
2. Add `server.port` Env to explicitly specify exposed port, because petclinic microservice will select random port in config server settings.
3. When a frontend app A has a call dependency on backend app B, it will add a Env `XXX_BASE_URL` to indicate it. Now I refer to the output of container app Bicep module, to make them topologized.

A few enhancements for deploy spring petclinic microservices

---

cli/azd/internal/appdetect/appdetect.go
cli/azd/internal/appdetect/spring_boot.go
cli/azd/internal/repository/app_init.go
cli/azd/internal/repository/app_init_test.go
cli/azd/internal/repository/infra_confirm.go
cli/azd/internal/repository/infra_confirm_test.go

User can get prompt when there is error about passwordless dependency or property.

User can get prompt when there is error about passwordless dependency or property.

---

cli/azd/.vscode/cspell.yaml
cli/azd/internal/appdetect/appdetect.go
cli/azd/internal/appdetect/appdetect_test.go
cli/azd/internal/appdetect/java.go
cli/azd/internal/appdetect/spring_boot.go
cli/azd/internal/appdetect/testdata/java-multimodules/mvnw
cli/azd/internal/appdetect/testdata/java-multimodules/mvnw.cmd
cli/azd/internal/repository/app_init.go

This project will fix the https://github.com/microsoft/SJAD sample:
- It will use the Maven wrapper in the project
- It will identify the web project as a frontend dependency

Fix SJAD sample

---

cli/azd/internal/appdetect/appdetect.go
cli/azd/internal/appdetect/spring_boot.go
cli/azd/internal/repository/app_init.go

Delete password check when using managed identity as auth type. Because the configured password will be ignored without and error.

Delete password check when using managed identity as auth type

---

cli/azd/internal/scaffold/spec_service_binding.go

when MI auth enabled (passwordless-enabled = true), we still need to manually set the password as empty. Otherwise, if source code set password, Jdbc will use password auth instead of MI auth.

Fix: manually set empty password when using MI auth

---

cli/azd/pkg/project/framework_service_docker.go

In a multi-module project, when the relative path of a sub-module contains `\`, it won't be identified by pack build, we need to convert the file path to unix format, not windows format.
For example, the relative path may be `eventhubs\spring-cloud-azure-starter\spring-cloud-azure-sample-eventhubs-kafka` in windows, we need to feed it as `eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka` into pack build.

Fix: convert sub-module relative path into unix format when pack build

---

cli/azd/internal/appdetect/appdetect.go
cli/azd/internal/appdetect/spring_boot.go
cli/azd/internal/repository/app_init.go

Before in the sample application, we use explicit variables in the application.yml.
When placeholder not detected in application.yml, prompt user to input.
To fix these samples:
- [single-binder](https://github.com/azure-javaee/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder)
- multi-binders:
- [spring2 sample](https://github.com/azure-javaee/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-multibinders/spring2sample)
- [spring3 sample](https://github.com/azure-javaee/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-multibinders/spring3sample)

When placeholder not detected in application.yml, prompt user to input

---

cli/azd/internal/appdetect/appdetect.go
cli/azd/internal/appdetect/spring_boot.go
cli/azd/internal/repository/app_init.go
cli/azd/internal/repository/infra_confirm.go

1. Move `NamePropertyMap` from into AzureDeps, not Metadata.
2. Resolve the placeholder of stream-kafka sample.
3. Support to detect `spring-cloud-azure-starter-eventhubs` dependency.
To fix the samples:
1. [Kafka sample with placeholder](https://github.com/azure-javaee/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka)
2. [EventHubs starter sample](https://github.com/azure-javaee/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-starter-eventhubs/eventhubs-client)

Enhancement: support to resolve placeholder for Kafka and detect eventhubs starter dependency

---

cli/azd/internal/appdetect/maven_command.go
cli/azd/internal/appdetect/maven_command_test.go
cli/azd/internal/appdetect/pom.go

1. Change the path of downloaded maven.
2. Fix error of mavenZipFileName.
3. Provide a new func: getMvnCommand, which does not need input a path.

Improve the code of maven command

---

cli/azd/internal/repository/app_init.go

Make message more clear when lack dependency.
Here is the screenshot of new message:
> ![image](https://github.com/user-attachments/assets/0e7fce7c-aef4-46fd-bcba-dc631223e7e2)

Make message more clear when lack dependency

---

cli/azd/internal/repository/app_init.go

when eureka server / config server removed during detect confirm, the client should be aware of this change.
+ don't add the useless envs.
+ don't add into `resources.uses` section.

Fix: the incorrect azure.yaml when eureka / config server removed

---

cli/azd/internal/scaffold/spec_service_binding.go

When service A uses service B, azd will inject the service url to each other,
In service A, the env looks like: serviceB_BASE_URL: <service B's url>
In service B, the env looks like: serviceA_BASE_URL: <service A's url>
Now there is a bug when injecting these Envs.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2326921

Fix the uses Env when injecting frontend and backends.

---

cli/azd/internal/appdetect/appdetect_test.go
cli/azd/internal/appdetect/java.go
cli/azd/internal/appdetect/testdata/java-multi-levels/mvnw
cli/azd/internal/appdetect/testdata/java-multi-levels/mvnw.cmd
cli/azd/internal/appdetect/testdata/java-multi-levels/pom.xml
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/pom.xml
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule1/pom.xml
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule1/src/main/java/com/example/subsubmodule1/Subsubmodule1Application.java
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule1/src/main/resources/application.properties
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule1/src/test/java/com/example/subsubmodule1/Subsubmodule1ApplicationTests.java
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule2/pom.xml
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule2/src/main/java/com/example/subsubmodule2/Subsubmodule2Application.java
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule2/src/main/resources/application.properties
cli/azd/internal/appdetect/testdata/java-multi-levels/submodule/subsubmodule2/src/test/java/com/example/subsubmodule2/Subsubmodule2ApplicationTests.java
cli/azd/internal/repository/app_init.go
cli/azd/pkg/project/framework_service_docker.go
cli/azd/pkg/project/service_config.go
schemas/alpha/azure.yaml.json

When pack build multi-module project, we have to specify the parent path as `build context`, and specify the sub-module path as `build module`. 
Here we should use accurate `parent path`, not the `project path`, because the project path maybe not the parent, like follows:
- [spring-petclinic-microservices](https://github.com/azure-javaee/spring-petclinic-microservices/tree/sjad?tab=readme-ov-file#starting-services-with-azd) is multi-module project, where the project path is the parent path.
- [app-templates-java-openai-springapps](https://github.com/Azure-Samples/app-templates-java-openai-springapps) is also a multi-module project, but it has no parent path, the project path is NOT parent path.

Fix: when pack build multi-module project, use actual parent path, instead of project path.

---

cli/azd/internal/appdetect/appdetect.go

Fix: Spring Frontend not displayed in detect confirm message.
The screenshot after fix:
> ![image](https://github.com/user-attachments/assets/2a0b8173-2d34-4b71-a821-e43c0ad996c6)

Fix: SpringFrontend not displayed in detect confirm message

---

cli/azd/internal/repository/app_init.go

Fix: Application name malformed causes `azd up` failing.
> ![image](https://github.com/user-attachments/assets/29baf210-afe8-4c61-94ee-6f5d0999a473)

Fix: Application name malformed causes `azd up` failing

---

cli/azd/internal/cmd/add/add_configure.go
cli/azd/internal/cmd/add/add_select.go
cli/azd/internal/scaffold/scaffold_test.go
cli/azd/resources/scaffold/templates/resources.bicept

Fix the `azd add` not working bug in sjad https://github.com/Azure/azure-dev/pull/4473#issuecomment-2585975197

Fix the azd add not working bug in sjad 

---

cli/azd/pkg/project/framework_service_docker.go

Fix the bug that app built by default Dockerfile cannot fetch Envs.
The root cause is that, use `sh -c` before, which make the command run in the shell context, and the Envs cannot work as expected. Now run the command directly and let Docker handle the command execution directly, ensuring the environment variables propagate correctly.
Test by running the https://github.com/azure-javaee/azure-spring-boot-samples/tree/main/postgresql/spring-cloud-azure-starter-jdbc-postgresql/spring-cloud-azure-postgresql-sample

Fix the bug that app built by default Dockerfile cannot fetch Envs
